### ISSUE TITLE
lbex Requires Restarting After Error

### ISSUE THREAD

**Issue by sostheim** [sostheim/lbex#56]
Panic in logfile:

```
- Logs begin at Thu 2017-08-17 22:49:48 UTC, end at Thu 2017-08-17 22:50:53 UTC. --
Aug 17 22:50:06 zonar-gke-001-lbex-fck1 systemd[1]: Starting Start lbex...
Aug 17 22:50:40 zonar-gke-001-lbex-fck1 tar[1951]: http.tmpl
Aug 17 22:50:40 zonar-gke-001-lbex-fck1 tar[1951]: lbex
Aug 17 22:50:41 zonar-gke-001-lbex-fck1 tar[1951]: nginx.conf.tmpl
Aug 17 22:50:41 zonar-gke-001-lbex-fck1 tar[1951]: stream.tmpl
Aug 17 22:50:42 zonar-gke-001-lbex-fck1 gcloud[1961]: Updated property [container/use_application_default_credentia
Aug 17 22:50:45 zonar-gke-001-lbex-fck1 gcloud[1977]: Fetching cluster endpoint and auth data.
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 gcloud[1977]: kubeconfig entry generated for zonar-gke-001.
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 systemd[1]: Started Start lbex.
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: user nginx nginx;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: worker_processes 2;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: events {
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:     worker_connections 512;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: }
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: stream {
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:     include /etc/nginx/conf.d/*.stream.conf;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: }
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: http {
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:     server {
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         listen 7331 default_server;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         server_name _;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         location / {
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:             access_log off;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:             default_type text/plain;
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:             return 200 "healthy\n";
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         }
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:     }
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: }
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: F0817 22:50:46.245205    1993 nginx.go:203] Failed to open /etc/nginx/nginx.conf: open /etc/nginx/nginx.conf: no such file or directory
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: goroutine 1 [running]:
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: github.com/samsung-cnct/lbex/vendor/github.com/golang/glog.stacks(0x1c73300, 0xc400000000, 0x88, 0xab)
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/vendor/github.com/golang/glog/glog.go:766 +0xa5
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: github.com/samsung-cnct/lbex/vendor/github.com/golang/glog.(*loggingT).output(0x1c530e0, 0xc400000003, 0xc420065bc0, 0x1bed6b2, 0x8, 0xcb, 0x0)
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/vendor/github.com/golang/glog/glog.go:717 +0x337
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: github.com/samsung-cnct/lbex/vendor/github.com/golang/glog.(*loggingT).printf(0x1c530e0, 0xc400000003, 0x143dd0f, 0x15, 0xc420475b08, 0x2, 0x2)
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/vendor/github.com/golang/glog/glog.go:655 +0x14c
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: github.com/samsung-cnct/lbex/vendor/github.com/golang/glog.Fatalf(0x143dd0f, 0x15, 0xc420475b08, 0x2, 0x2)
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/vendor/github.com/golang/glog/glog.go:1145 +0x67
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: github.com/samsung-cnct/lbex/nginx.(*NginxController).UpdateMainConfigFile(0xc4202aef30)
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/nginx/nginx.go:203 +0x3cc
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: github.com/samsung-cnct/lbex/nginx.NewNginxController(0x1, 0x1430fa3, 0xb, 0xc42042b601, 0x1ca3, 0xc4203af5a0, 0x0, 0x0)
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/nginx/nginx.go:128 +0x31b
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: main.newLbExController(0xc420252770, 0xc4203ec780, 0x1b)
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/controller.go:79 +0x6f
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]: main.main()
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 lbex[1993]:         /Users/marat/dev/go/src/github.com/samsung-cnct/lbex/main.go:128 +0x1e4
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 systemd[1]: lbex.service: Main process exited, code=exited, status=255/n/a
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 systemd[1]: lbex.service: Unit entered failed state.
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 systemd[1]: lbex.service: Failed with result 'exit-code'.
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 systemd[1]: lbex.service: Service hold-off time over, scheduling restart.
Aug 17 22:50:46 zonar-gke-001-lbex-fck1 systemd[1]: Stopped Start lbex.
```

**Comment by sostheim** [comment]
@maratoid /cc
